In [1]:
%matplotlib inline

# 什么是 PyTorch?

它是一个基于Python的科学计算软件包，针对两组受众：

- NumPy 的替代品，可以使用 GPU 的强大功能
- 深度学习研究平台，提供最大的灵活性和速度


## 开始


### 张量(Tensor)

Tensor(张量)类似于 NumPy 的 ndarrays(多维数组)，不过 Tensor 可以使用 GPU 加速计算。


In [2]:
from __future__ import print_function
import torch


构造一个未初始化的5x3矩阵：


In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.2720e+08,  4.5715e-41, -1.2720e+08],
        [ 4.5715e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  3.5873e-43],
        [ 0.0000e+00,  1.7937e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])



构造一个随机初始化的矩阵：


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7537, 0.3162, 0.4814],
        [0.4303, 0.2807, 0.0952],
        [0.6169, 0.8890, 0.9761],
        [0.8800, 0.2198, 0.3990],
        [0.2434, 0.9329, 0.5439]])



构造一个零填充，数据类型(`dtype`)为长整形(`long`)的矩阵:


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])



直接从数据构造 tensor:


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])



或者在已有 tensor 的基础上创建 tensor。 这种方法将重用输入 tensor 的属性，如 `dtype`, 除非提供新的值


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3971, -0.0788, -1.4905],
        [-0.1972,  2.7935, -1.8287],
        [-0.9228,  0.2789, -1.0781],
        [ 0.4243, -2.0406, -0.5721],
        [-0.8084, -0.3740, -0.5767]])


获取其大小:

In [8]:
print(x.size())

torch.Size([5, 3])



> **注意**:
>
> `torch.Size` 是 tuple(元组)，它支持所有 tuple 操作。


### 运算

运算有多种语法。在下面的示例中，我们将看一看加法运算



加法: 语法 1


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0884,  0.3262, -0.6358],
        [-0.1748,  3.5457, -1.4837],
        [-0.3640,  0.7406, -0.4035],
        [ 1.2890, -1.2470,  0.2520],
        [ 0.1289,  0.4050,  0.0856]])



加法: 语法 2


In [10]:
print(torch.add(x, y))

tensor([[ 1.0884,  0.3262, -0.6358],
        [-0.1748,  3.5457, -1.4837],
        [-0.3640,  0.7406, -0.4035],
        [ 1.2890, -1.2470,  0.2520],
        [ 0.1289,  0.4050,  0.0856]])



加法: 将输出 tensor 作为参数


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0884,  0.3262, -0.6358],
        [-0.1748,  3.5457, -1.4837],
        [-0.3640,  0.7406, -0.4035],
        [ 1.2890, -1.2470,  0.2520],
        [ 0.1289,  0.4050,  0.0856]])



加法: 原位修改


In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0884,  0.3262, -0.6358],
        [-0.1748,  3.5457, -1.4837],
        [-0.3640,  0.7406, -0.4035],
        [ 1.2890, -1.2470,  0.2520],
        [ 0.1289,  0.4050,  0.0856]])



> **注意**:
>
> 任何原位修改 tensor 的运算方法都是以 `_` 结尾的。
> 例如：`x.copy_(y)`，`x.t_()` ，会改变 `x`



可以使用类似 NumPy 的索引运算！


In [13]:
print(x[:, 1])

tensor([-0.0788,  2.7935,  0.2789, -2.0406, -0.3740])



调整大小：如果要对 tensor 调整大小/改变形状，可以使用 `torch.view`:


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])



对于只有一个元素的 tensor，可以用 `.item()` 得到这个值对应的 Python 数值


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8057])
-0.8056557774543762



> **延后阅读**：
>
> 100+ Tensor 运算，包括：移调、索引、切片、数学运算、线性代数、随机数等，可参考 <https://pytorch.org/docs/torch>


## NumPy 转换

将 Torch Tensor 转换为 NumPy 数组（反之亦然）是一件轻而易举的事。

Torch Tensor 和 NumPy 数组共享其底层内存位置，更改一个会导致另一个的改变。


### 将 Torch Tensor 转换为 NumPy 数组

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]



了解numpy数组的值如何变化。


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 将 NumPy 数组转换为 Torch Tensor

了解更改 NumPy 数组如何自动更改 Torch Tensor


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



除了 `CharTensor` ，所有 CPU 上的 Tensor 都可以和 Numpy 互相转换。


## CUDA Tensors

可以使用 `.to` 方法移动 Tensors 到任何设备。


In [20]:
# 只有 CUDA 可用时，才运行这个 cell
# 使用 ``torch.device`` 对象将 tensor 移入以及移出 GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接在 GPU 上创建 tensor
    x = x.to(device)                       # 或者用 ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也可以同时更改 ``dtype``!

tensor([0.1943], device='cuda:0')
tensor([0.1943], dtype=torch.float64)
